name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container
        run: docker build -t user-api:latest .

  sbom-and-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SBOM (syft)
        uses: anchore/syft-action@v0.10.0
        with:
          image: user-api:latest

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@v0.8.0
        with:
          image-ref: user-api:latest
          exit-code: '1'

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1

      - name: Gitleaks (secret detection)
        uses: zricethezav/gitleaks-action@v2
